sudo: false

language: java

services:
  - docker

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn package

addons:
  artifacts:
    paths:
      - $(ls nifi-minio-nar/target/nifi-minio*.nar)

cache:
  directories:
  - "$HOME/.cache"
